// ref. https://highlightjs.org/static/demo/
export const themes = [
  { name: 'Default', theme: 'default' },
	{ name: 'A 11 Y Dark', theme: 'a11y-dark' },
	{ name: 'A 11 Y Light', theme: 'a11y-light' },
	{ name: 'Agate', theme: 'agate' },
	{ name: 'An Old Hope', theme: 'an-old-hope' },
	{ name: 'Androidstudio', theme: 'androidstudio' },
	{ name: 'Arduino Light', theme: 'arduino-light' },
	{ name: 'Arta', theme: 'arta' },
	{ name: 'Ascetic', theme: 'ascetic' },
	{ name: 'Atom One Dark', theme: 'atom-one-dark' },
	{ name: 'Atom One Dark Reasonable', theme: 'atom-one-dark-reasonable' },
	{ name: 'Atom One Light', theme: 'atom-one-light' },
	{ name: 'Base16 / 3024', theme: 'base16/3024' },
	{ name: 'Base16 / Apathy', theme: 'base16/apathy' },
	{ name: 'Base16 / Apprentice', theme: 'base16/apprentice' },
	{ name: 'Base16 / Ashes', theme: 'base16/ashes' },
	{ name: 'Base16 / Atelier Cave', theme: 'base16/atelier-cave' },
	{ name: 'Base16 / Atelier Cave Light', theme: 'base16/atelier-cave-light' },
	{ name: 'Base16 / Atelier Dune', theme: 'base16/atelier-dune' },
	{ name: 'Base16 / Atelier Dune Light', theme: 'base16/atelier-dune-light' },
	{ name: 'Base16 / Atelier Estuary', theme: 'base16/atelier-estuary' },
	{
		name: 'Base16 / Atelier Estuary Light',
		theme: 'base16/atelier-estuary-light'
	},
	{ name: 'Base16 / Atelier Forest', theme: 'base16/atelier-forest' },
	{
		name: 'Base16 / Atelier Forest Light',
		theme: 'base16/atelier-forest-light'
	},
	{ name: 'Base16 / Atelier Heath', theme: 'base16/atelier-heath' },
	{ name: 'Base16 / Atelier Heath Light', theme: 'base16/atelier-heath-light' },
	{ name: 'Base16 / Atelier Lakeside', theme: 'base16/atelier-lakeside' },
	{
		name: 'Base16 / Atelier Lakeside Light',
		theme: 'base16/atelier-lakeside-light'
	},
	{ name: 'Base16 / Atelier Plateau', theme: 'base16/atelier-plateau' },
	{
		name: 'Base16 / Atelier Plateau Light',
		theme: 'base16/atelier-plateau-light'
	},
	{ name: 'Base16 / Atelier Savanna', theme: 'base16/atelier-savanna' },
	{
		name: 'Base16 / Atelier Savanna Light',
		theme: 'base16/atelier-savanna-light'
	},
	{ name: 'Base16 / Atelier Seaside', theme: 'base16/atelier-seaside' },
	{
		name: 'Base16 / Atelier Seaside Light',
		theme: 'base16/atelier-seaside-light'
	},
	{ name: 'Base16 / Atelier Sulphurpool', theme: 'base16/atelier-sulphurpool' },
	{
		name: 'Base16 / Atelier Sulphurpool Light',
		theme: 'base16/atelier-sulphurpool-light'
	},
	{ name: 'Base16 / Atlas', theme: 'base16/atlas' },
	{ name: 'Base16 / Bespin', theme: 'base16/bespin' },
	{ name: 'Base16 / Black Metal', theme: 'base16/black-metal' },
	{ name: 'Base16 / Black Metal Bathory', theme: 'base16/black-metal-bathory' },
	{ name: 'Base16 / Black Metal Burzum', theme: 'base16/black-metal-burzum' },
	{
		name: 'Base16 / Black Metal Dark Funeral',
		theme: 'base16/black-metal-dark-funeral'
	},
	{
		name: 'Base16 / Black Metal Gorgoroth',
		theme: 'base16/black-metal-gorgoroth'
	},
	{
		name: 'Base16 / Black Metal Immortal',
		theme: 'base16/black-metal-immortal'
	},
	{ name: 'Base16 / Black Metal Khold', theme: 'base16/black-metal-khold' },
	{ name: 'Base16 / Black Metal Marduk', theme: 'base16/black-metal-marduk' },
	{ name: 'Base16 / Black Metal Mayhem', theme: 'base16/black-metal-mayhem' },
	{ name: 'Base16 / Black Metal Nile', theme: 'base16/black-metal-nile' },
	{ name: 'Base16 / Black Metal Venom', theme: 'base16/black-metal-venom' },
	{ name: 'Base16 / Brewer', theme: 'base16/brewer' },
	{ name: 'Base16 / Bright', theme: 'base16/bright' },
	{ name: 'Base16 / Brogrammer', theme: 'base16/brogrammer' },
	{ name: 'Base16 / Brush Trees', theme: 'base16/brush-trees' },
	{ name: 'Base16 / Brush Trees Dark', theme: 'base16/brush-trees-dark' },
	{ name: 'Base16 / Chalk', theme: 'base16/chalk' },
	{ name: 'Base16 / Circus', theme: 'base16/circus' },
	{ name: 'Base16 / Classic Dark', theme: 'base16/classic-dark' },
	{ name: 'Base16 / Classic Light', theme: 'base16/classic-light' },
	{ name: 'Base16 / Codeschool', theme: 'base16/codeschool' },
	{ name: 'Base16 / Colors', theme: 'base16/colors' },
	{ name: 'Base16 / Cupcake', theme: 'base16/cupcake' },
	{ name: 'Base16 / Cupertino', theme: 'base16/cupertino' },
	{ name: 'Base16 / Danqing', theme: 'base16/danqing' },
	{ name: 'Base16 / Darcula', theme: 'base16/darcula' },
	{ name: 'Base16 / Dark Violet', theme: 'base16/dark-violet' },
	{ name: 'Base16 / Darkmoss', theme: 'base16/darkmoss' },
	{ name: 'Base16 / Darktooth', theme: 'base16/darktooth' },
	{ name: 'Base16 / Decaf', theme: 'base16/decaf' },
	{ name: 'Base16 / Default Dark', theme: 'base16/default-dark' },
	{ name: 'Base16 / Default Light', theme: 'base16/default-light' },
	{ name: 'Base16 / Dirtysea', theme: 'base16/dirtysea' },
	{ name: 'Base16 / Dracula', theme: 'base16/dracula' },
	{ name: 'Base16 / Edge Dark', theme: 'base16/edge-dark' },
	{ name: 'Base16 / Edge Light', theme: 'base16/edge-light' },
	{ name: 'Base16 / Eighties', theme: 'base16/eighties' },
	{ name: 'Base16 / Embers', theme: 'base16/embers' },
	{ name: 'Base16 / Equilibrium Dark', theme: 'base16/equilibrium-dark' },
	{
		name: 'Base16 / Equilibrium Gray Dark',
		theme: 'base16/equilibrium-gray-dark'
	},
	{
		name: 'Base16 / Equilibrium Gray Light',
		theme: 'base16/equilibrium-gray-light'
	},
	{ name: 'Base16 / Equilibrium Light', theme: 'base16/equilibrium-light' },
	{ name: 'Base16 / Espresso', theme: 'base16/espresso' },
	{ name: 'Base16 / Eva', theme: 'base16/eva' },
	{ name: 'Base16 / Eva Dim', theme: 'base16/eva-dim' },
	{ name: 'Base16 / Flat', theme: 'base16/flat' },
	{ name: 'Base16 / Framer', theme: 'base16/framer' },
	{ name: 'Base16 / Fruit Soda', theme: 'base16/fruit-soda' },
	{ name: 'Base16 / Gigavolt', theme: 'base16/gigavolt' },
	{ name: 'Base16 / Github', theme: 'base16/github' },
	{ name: 'Base16 / Google Dark', theme: 'base16/google-dark' },
	{ name: 'Base16 / Google Light', theme: 'base16/google-light' },
	{ name: 'Base16 / Grayscale Dark', theme: 'base16/grayscale-dark' },
	{ name: 'Base16 / Grayscale Light', theme: 'base16/grayscale-light' },
	{ name: 'Base16 / Green Screen', theme: 'base16/green-screen' },
	{ name: 'Base16 / Gruvbox Dark Hard', theme: 'base16/gruvbox-dark-hard' },
	{ name: 'Base16 / Gruvbox Dark Medium', theme: 'base16/gruvbox-dark-medium' },
	{ name: 'Base16 / Gruvbox Dark Pale', theme: 'base16/gruvbox-dark-pale' },
	{ name: 'Base16 / Gruvbox Dark Soft', theme: 'base16/gruvbox-dark-soft' },
	{ name: 'Base16 / Gruvbox Light Hard', theme: 'base16/gruvbox-light-hard' },
	{
		name: 'Base16 / Gruvbox Light Medium',
		theme: 'base16/gruvbox-light-medium'
	},
	{ name: 'Base16 / Gruvbox Light Soft', theme: 'base16/gruvbox-light-soft' },
	{ name: 'Base16 / Hardcore', theme: 'base16/hardcore' },
	{ name: 'Base16 / Harmonic 16 Dark', theme: 'base16/harmonic16-dark' },
	{ name: 'Base16 / Harmonic 16 Light', theme: 'base16/harmonic16-light' },
	{ name: 'Base16 / Heetch Dark', theme: 'base16/heetch-dark' },
	{ name: 'Base16 / Heetch Light', theme: 'base16/heetch-light' },
	{ name: 'Base16 / Helios', theme: 'base16/helios' },
	{ name: 'Base16 / Hopscotch', theme: 'base16/hopscotch' },
	{ name: 'Base16 / Horizon Dark', theme: 'base16/horizon-dark' },
	{ name: 'Base16 / Horizon Light', theme: 'base16/horizon-light' },
	{ name: 'Base16 / Humanoid Dark', theme: 'base16/humanoid-dark' },
	{ name: 'Base16 / Humanoid Light', theme: 'base16/humanoid-light' },
	{ name: 'Base16 / Ia Dark', theme: 'base16/ia-dark' },
	{ name: 'Base16 / Ia Light', theme: 'base16/ia-light' },
	{ name: 'Base16 / Icy Dark', theme: 'base16/icy-dark' },
	{ name: 'Base16 / Ir Black', theme: 'base16/ir-black' },
	{ name: 'Base16 / Isotope', theme: 'base16/isotope' },
	{ name: 'Base16 / Kimber', theme: 'base16/kimber' },
	{ name: 'Base16 / London Tube', theme: 'base16/london-tube' },
	{ name: 'Base16 / Macintosh', theme: 'base16/macintosh' },
	{ name: 'Base16 / Marrakesh', theme: 'base16/marrakesh' },
	{ name: 'Base16 / Materia', theme: 'base16/materia' },
	{ name: 'Base16 / Material', theme: 'base16/material' },
	{ name: 'Base16 / Material Darker', theme: 'base16/material-darker' },
	{ name: 'Base16 / Material Lighter', theme: 'base16/material-lighter' },
	{ name: 'Base16 / Material Palenight', theme: 'base16/material-palenight' },
	{ name: 'Base16 / Material Vivid', theme: 'base16/material-vivid' },
	{ name: 'Base16 / Mellow Purple', theme: 'base16/mellow-purple' },
	{ name: 'Base16 / Mexico Light', theme: 'base16/mexico-light' },
	{ name: 'Base16 / Mocha', theme: 'base16/mocha' },
	{ name: 'Base16 / Monokai', theme: 'base16/monokai' },
	{ name: 'Base16 / Nebula', theme: 'base16/nebula' },
	{ name: 'Base16 / Nord', theme: 'base16/nord' },
	{ name: 'Base16 / Nova', theme: 'base16/nova' },
	{ name: 'Base16 / Ocean', theme: 'base16/ocean' },
	{ name: 'Base16 / Oceanicnext', theme: 'base16/oceanicnext' },
	{ name: 'Base16 / One Light', theme: 'base16/one-light' },
	{ name: 'Base16 / Onedark', theme: 'base16/onedark' },
	{ name: 'Base16 / Outrun Dark', theme: 'base16/outrun-dark' },
	{ name: 'Base16 / Papercolor Dark', theme: 'base16/papercolor-dark' },
	{ name: 'Base16 / Papercolor Light', theme: 'base16/papercolor-light' },
	{ name: 'Base16 / Paraiso', theme: 'base16/paraiso' },
	{ name: 'Base16 / Pasque', theme: 'base16/pasque' },
	{ name: 'Base16 / Phd', theme: 'base16/phd' },
	{ name: 'Base16 / Pico', theme: 'base16/pico' },
	{ name: 'Base16 / Pop', theme: 'base16/pop' },
	{ name: 'Base16 / Porple', theme: 'base16/porple' },
	{ name: 'Base16 / Qualia', theme: 'base16/qualia' },
	{ name: 'Base16 / Railscasts', theme: 'base16/railscasts' },
	{ name: 'Base16 / Rebecca', theme: 'base16/rebecca' },
	{ name: 'Base16 / Ros Pine', theme: 'base16/ros-pine' },
	{ name: 'Base16 / Ros Pine Dawn', theme: 'base16/ros-pine-dawn' },
	{ name: 'Base16 / Ros Pine Moon', theme: 'base16/ros-pine-moon' },
	{ name: 'Base16 / Sagelight', theme: 'base16/sagelight' },
	{ name: 'Base16 / Sandcastle', theme: 'base16/sandcastle' },
	{ name: 'Base16 / Seti Ui', theme: 'base16/seti-ui' },
	{ name: 'Base16 / Shapeshifter', theme: 'base16/shapeshifter' },
	{ name: 'Base16 / Silk Dark', theme: 'base16/silk-dark' },
	{ name: 'Base16 / Silk Light', theme: 'base16/silk-light' },
	{ name: 'Base16 / Snazzy', theme: 'base16/snazzy' },
	{ name: 'Base16 / Solar Flare', theme: 'base16/solar-flare' },
	{ name: 'Base16 / Solar Flare Light', theme: 'base16/solar-flare-light' },
	{ name: 'Base16 / Solarized Dark', theme: 'base16/solarized-dark' },
	{ name: 'Base16 / Solarized Light', theme: 'base16/solarized-light' },
	{ name: 'Base16 / Spacemacs', theme: 'base16/spacemacs' },
	{ name: 'Base16 / Summercamp', theme: 'base16/summercamp' },
	{ name: 'Base16 / Summerfruit Dark', theme: 'base16/summerfruit-dark' },
	{ name: 'Base16 / Summerfruit Light', theme: 'base16/summerfruit-light' },
	{
		name: 'Base16 / Synth Midnight Terminal Dark',
		theme: 'base16/synth-midnight-terminal-dark'
	},
	{
		name: 'Base16 / Synth Midnight Terminal Light',
		theme: 'base16/synth-midnight-terminal-light'
	},
	{ name: 'Base16 / Tango', theme: 'base16/tango' },
	{ name: 'Base16 / Tender', theme: 'base16/tender' },
	{ name: 'Base16 / Tomorrow', theme: 'base16/tomorrow' },
	{ name: 'Base16 / Tomorrow Night', theme: 'base16/tomorrow-night' },
	{ name: 'Base16 / Twilight', theme: 'base16/twilight' },
	{ name: 'Base16 / Unikitty Dark', theme: 'base16/unikitty-dark' },
	{ name: 'Base16 / Unikitty Light', theme: 'base16/unikitty-light' },
	{ name: 'Base16 / Vulcan', theme: 'base16/vulcan' },
	{ name: 'Base16 / Windows 10', theme: 'base16/windows-10' },
	{ name: 'Base16 / Windows 10 Light', theme: 'base16/windows-10-light' },
	{ name: 'Base16 / Windows 95', theme: 'base16/windows-95' },
	{ name: 'Base16 / Windows 95 Light', theme: 'base16/windows-95-light' },
	{
		name: 'Base16 / Windows High Contrast',
		theme: 'base16/windows-high-contrast'
	},
	{
		name: 'Base16 / Windows High Contrast Light',
		theme: 'base16/windows-high-contrast-light'
	},
	{ name: 'Base16 / Windows Nt', theme: 'base16/windows-nt' },
	{ name: 'Base16 / Windows Nt Light', theme: 'base16/windows-nt-light' },
	{ name: 'Base16 / Woodland', theme: 'base16/woodland' },
	{ name: 'Base16 / Xcode Dusk', theme: 'base16/xcode-dusk' },
	{ name: 'Base16 / Zenburn', theme: 'base16/zenburn' },
	{ name: 'Brown Paper', theme: 'brown-paper' },
	{ name: 'Codepen Embed', theme: 'codepen-embed' },
	{ name: 'Color Brewer', theme: 'color-brewer' },
	{ name: 'Dark', theme: 'dark' },
	{ name: 'Devibeans', theme: 'devibeans' },
	{ name: 'Docco', theme: 'docco' },
	{ name: 'Far', theme: 'far' },
	{ name: 'Felipec', theme: 'felipec' },
	{ name: 'Foundation', theme: 'foundation' },
	{ name: 'Github', theme: 'github' },
	{ name: 'Github Dark', theme: 'github-dark' },
	{ name: 'Github Dark Dimmed', theme: 'github-dark-dimmed' },
	{ name: 'Gml', theme: 'gml' },
	{ name: 'Googlecode', theme: 'googlecode' },
	{ name: 'Gradient Dark', theme: 'gradient-dark' },
	{ name: 'Gradient Light', theme: 'gradient-light' },
	{ name: 'Grayscale', theme: 'grayscale' },
	{ name: 'Hybrid', theme: 'hybrid' },
	{ name: 'Idea', theme: 'idea' },
	{ name: 'Intellij Light', theme: 'intellij-light' },
	{ name: 'Ir Black', theme: 'ir-black' },
	{ name: 'Isbl Editor Dark', theme: 'isbl-editor-dark' },
	{ name: 'Isbl Editor Light', theme: 'isbl-editor-light' },
	{ name: 'Kimbie Dark', theme: 'kimbie-dark' },
	{ name: 'Kimbie Light', theme: 'kimbie-light' },
	{ name: 'Lightfair', theme: 'lightfair' },
	{ name: 'Lioshi', theme: 'lioshi' },
	{ name: 'Magula', theme: 'magula' },
	{ name: 'Mono Blue', theme: 'mono-blue' },
	{ name: 'Monokai', theme: 'monokai' },
	{ name: 'Monokai Sublime', theme: 'monokai-sublime' },
	{ name: 'Night Owl', theme: 'night-owl' },
	{ name: 'Nnfx Dark', theme: 'nnfx-dark' },
	{ name: 'Nnfx Light', theme: 'nnfx-light' },
	{ name: 'Nord', theme: 'nord' },
	{ name: 'Obsidian', theme: 'obsidian' },
	{ name: 'Panda Syntax Dark', theme: 'panda-syntax-dark' },
	{ name: 'Panda Syntax Light', theme: 'panda-syntax-light' },
	{ name: 'Paraiso Dark', theme: 'paraiso-dark' },
	{ name: 'Paraiso Light', theme: 'paraiso-light' },
	{ name: 'Pojoaque', theme: 'pojoaque' },
	{ name: 'Purebasic', theme: 'purebasic' },
	{ name: 'Qtcreator Dark', theme: 'qtcreator-dark' },
	{ name: 'Qtcreator Light', theme: 'qtcreator-light' },
	{ name: 'Rainbow', theme: 'rainbow' },
	{ name: 'Routeros', theme: 'routeros' },
	{ name: 'School Book', theme: 'school-book' },
	{ name: 'Shades Of Purple', theme: 'shades-of-purple' },
	{ name: 'Srcery', theme: 'srcery' },
	{ name: 'Stackoverflow Dark', theme: 'stackoverflow-dark' },
	{ name: 'Stackoverflow Light', theme: 'stackoverflow-light' },
	{ name: 'Sunburst', theme: 'sunburst' },
	{ name: 'Tokyo Night Dark', theme: 'tokyo-night-dark' },
	{ name: 'Tokyo Night Light', theme: 'tokyo-night-light' },
	{ name: 'Tomorrow Night Blue', theme: 'tomorrow-night-blue' },
	{ name: 'Tomorrow Night Bright', theme: 'tomorrow-night-bright' },
	{ name: 'Vs', theme: 'vs' },
	{ name: 'Vs 2015', theme: 'vs2015' },
	{ name: 'Xcode', theme: 'xcode' },
	{ name: 'Xt 256', theme: 'xt256' }
];
